# Generated by Django 3.2.6 on 2021-09-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=6),
            preserve_default=False,
        ),
    ]
