# Generated by Django 3.2.6 on 2021-09-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='age',
            field=models.DecimalField(decimal_places=0, default=18, max_digits=2),
            preserve_default=False,
        ),
    ]
